language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: basic-softeng-webapp
  api_key:
    secure: G62pNCJnP5XqHfZqLUCkczaM/CMC/tEBOlPaR+scSTwQiDOMwwQ6cjZganvrXq4HL4Lyoq5T268o/3TD6mk0KZ+UAa1DjCgCg97F7J1zrGFmMgPshVWTS/TIzkUQzzPsOfE7aMf0sMXNbpdQi2zM74zkFMx6n6PmR5g4dekJ59KRD04NjrjtgTjvwEhiI32bYC9L1IXG+KRr601ETVmfdXC2SdQVq4hX292/9JSUhCYEafvmZDXFRQ7FrNiLQRAPfaMxcqy8oExl+WlhBpl6MK3fOVwtpQCiM+0anRnq+2spDKxhTXQLU/Do0c8hefniTdpjSKBO/PpWK0WKGDUALxE7CzYtdVsbwAhDc4PQUqMb4jZZJgxVa0b/9XsQc3ev52U02/3nj2ozK4QY83d2JbidWwPFKsMizQSYQqRhNi67i9v6ozyu2TL9Y/UB+52OEeyPf/4apeSTWXyal8QomcyoLlRdt0m9CeejgY5L6Q1cj1M8X0CKbjbZ1BYKS4L4EDdQjkUsM3apzwBZ1aDsmJp7AGIpO8E/E4iPYpRbVKSRQ/u6eZuOMwb0LHaVO6OMa7yhKOdU76wzz1jT0jBaHiLPLtsNMDqQLiURt/aJgeea5JOF0spf2quWPbKF7L2J2qncz4jYT4x+Ge0HcpndhhvC6ufVZIrDCwmE2Mr7+HQ=
